# .readthedocs.yml

# Required fields
version: 2

sphinx:
  configuration: docs/source/conf.py

# Optionally set the Python version and other settings
python:
  version: 3.8
  install:
    - requirements: requirements.txt
    - method: pip


