# .readthedocs.yml

# Required fields
version: 2

# Build documentation in the 'docs/' directory with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Optionally set the Python version and other settings
python:
  version: 3.8
  install:
    - requirements: requirements.txt
    - method: pip
      path: .


