# .readthedocs.yml

# Required fields
version: 2


build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

    
sphinx:
  configuration: docs/source/conf.py

# Optionally set the Python version and other settings
python:
  version: "3.8"
  install:
    - requirements: docs/requirements.txt


