# SPDX-FileCopyrightText: Florian Maurer, Christian Rieke
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version: "3"
services:
  open-data-16:
    image: timescale/timescaledb-ha:pg16-oss
    container_name: open-data-16
    restart: always
    shm_size: 32g
    command: postgres -c 'max_connections=6000' -c 'timescaledb.max_background_workers=32' -c 'timescaledb.telemetry_level=off'
    environment:
      - POSTGRES_USER=opendata
      - POSTGRES_PASSWORD=opendata
      - POSTGRES_DB=opendata
    volumes:
      - ./data/open-data-ha:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "6432:5432"

  pgadmin:
  # WINDOWS PERMISSIONS BODGE
    user: root
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.admin
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_LISTEN_PORT: 80
        PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
    volumes:
        - ./data/pgadmin:/var/lib/pgadmin
    ports:
        - "8080:80"

  open-postgrest:
     image: postgrest/postgrest:latest
     container_name: postgrest
     ports:
       - "3001:3000"
     environment:
       PGRST_DB_URI: postgres://readonly:readonly@open-data-16:5432/opendata
       PGRST_DB_PRE_CONFIG: postgrest.pre_config
       PGRST_DB_ANON_ROLE: readonly
       PGRST_DB_AGGREGATES_ENABLED: True
     depends_on:
       - open-data-16

  dashboard:
  # TODO VA ASK FLORIAN HOW BEST TO DO THI
    image: docker.io/library/dashboard
    container_name: dashboard-frontend
    ports:
      - "3004:3000"
    depends_on:
      - open-postgrest