version: "3"
services:
  open-data-14:
    image: timescale/timescaledb-ha:pg15-oss-latest
    container_name: open-data-15
    restart: always
    shm_size: 32g
    command: postgres -c "max_connections=2000" -c "timescaledb.max_background_workers=32" -c "timescaledb.telemetry_level=off"
    environment:
      - POSTGRES_USER=opendata
      - POSTGRES_PASSWORD=opendata
      - POSTGRES_DB=postgres  
    volumes:
      - ./data/open-data-ha:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.admin
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_LISTEN_PORT: 80
        PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
    volumes:
        - ./data/pgadmin:/var/lib/pgadmin
    ports:
        - "8080:80"
