site_name: Open Energy Data Server
site_url: https://github.com/NOWUM/open-energy-data-server/new/main
site_description: This is a repository that contains python web-crawler scripts to download various available data, which is useful for simulation or analysis of Energy Systems. The main target is to create an institute-wide available database that can be set up once and then be used by multiple researchers.
site_author: NOWUM-Energy Institute
theme:
  name: material

nav:
  - Home: README.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
